### ISSUE TITLE
unexpected behaviour by clicking back button on backup mode

### ISSUE THREAD

**Issue by kas84** [mjwheatley/cordova-plugin-android-fingerprint-auth#41]
Hi, I was expecting that clicking on back button on this screen would take me back to the fingerprint scanner back again, instead it results cancelled the same way if I pressed "cancel". Is this okay? Shouldn't it go back to the previous screen so it doesn't break the back button behaviour?

![screenshot_20161226-162355](https://cloud.githubusercontent.com/assets/5584/21483757/18425424-cb88-11e6-91b6-bdfca5f248cc.png)

(I was expecting to go back to this screen)
![screenshot_20161226-162533](https://cloud.githubusercontent.com/assets/5584/21483777/72359234-cb88-11e6-94ff-050e7623a4cc.png)

**Comment by mjwheatley** [comment]
I'm not sure it should.  The previous screen in this case was the calling Activity (the Cordova Webview, your app).  This plugin presents a Dialog Fragment on top of the calling Activity.  Whenever you make a selection from a dialog, the dialog is typically dismissed.  In this case, the user chose to open the backup credentials Activity and the dialog was dismissed.  So the only thing to go back to is your application.  This is the expected behavior.
