### ISSUE TITLE
Failure when fingerprint auth is shown in application and system lockscreen locks phone

### ISSUE THREAD

**Issue by szankelDvag** [mjwheatley/cordova-plugin-android-fingerprint-auth#64]
When fingerprint auth is shown in the application and system lockscreen locks the phone it is not possible to unlock with fingerprint.

**Comment by mjwheatley** [comment]
Please describe your issue in more detail and provide steps to reproduce the issue.  Please also list the device models you have tested.

**Comment by szankelDvag** [comment]
Our app has some lockscreen that can be unlocked using fingerprint. The time is settable via settings. After the time has passed and user didn't touch the view the app locks:

Steps to repdouce:

Start
Wait 31 seconds
-> App is not locked
-> Screen gets black
Unlock system lock screen with fingerprint
-> Device is unlocked
Wait 31 seconds (period is set to 1 minute)
-> Application lockscreen shows up with prompt to unlock via fingerprint
-> Wait screen gets black
Try to unlock system lock with fingerprint
-> Error: System doesn't accept fingerprint instead goes to enable via code

![_thumb_263326](https://cloud.githubusercontent.com/assets/24840265/24108747/d5181eba-0d8e-11e7-9ae2-25de3091612b.png)

**Comment by mjwheatley** [comment]
Here are my findings:

* Launch Fingerprint Authentication Dialog
* Hit power button to immediately lock the device (or wait until screen shuts off and locks)
* Touch fingerprint sensor to wake and unlock phone
    * Received touch vibration, screen turns on, shows "Confirm your password" screen.
        * Touch fingerprint sensor to unlock phone
        * Enter password to unlock phone
* Phone unlocks and resumes app
    * Fingerprint Auth Dialog is not showing

### Conclusion
* The Fingerprint Auth Dialog has registered a touch listener for the fingerprint sensor so the first time  the fingerprint sensor is touched to unlock the phone triggers the dialog's callback instead of unlocking the device.
* Even though the "Confirm your password" screen appears, user is still able to unlock the device with a fingerprint by touching the sensor a second time (Unknown if this is device specific).
*  After unlocking the device the application resumes and the authentication dialog has been closed.  User will need to reinitiate authentication request.

#### I find these results acceptable and have determined this is not an issue with the plugin.
