### ISSUE TITLE
Fingerprint dialog not canceled when pressing home button

### ISSUE THREAD

**Issue by rickgoud** [mjwheatley/cordova-plugin-android-fingerprint-auth#76]
I trigger the fingerprint on onresume and onstart. But when I press the home button and then restart my app the onresume puts another dialog above the one that was already there. Appereantly the initial dialog isn't closed at the on pause event. Can anyone tell me how to do that? I need to call the dialog at onresume when the time since the onpause was more than 15 minutes ago.

Thanks in advance!

**Comment by mjwheatley** [comment]
You need to track this in your app.  Store a timestamp before opening the FingerprintAuth dialog.  If the timestamp exists (dialog has been opened) and is within your accepted timeframe then don't open the dialog again.  Make sure to clear the timestamp appropriately.

I'm going to go ahead and close this issue because it is just an implementation question.

**Comment by sarahsga** [comment]
I am also triggering the fingerprint in onResume. I don't open the dialog again after onResume if it is already open. But, the already open dialog does not fire any callback, neither on authentication success nor on failure.
