### ISSUE TITLE
New_Fingerprints_Enrolled issue :-  Failed to init Cipher : invalidKeyException

### ISSUE THREAD

**Issue by rakeshpalivela** [mjwheatley/cordova-plugin-android-fingerprint-auth#9]
Hi,

Issue 1 : 
When I add new Finger Prints in my device, then I am getting the following exception.

Failed to init Cipher : invalidKeyException

If I changed my ClientID and Key then it was working fine...

So, can I know what it is doing after adding finger prints ....? 

Issue 2 : 

If I placed wrong finger, it allows up to five attempts after that I waited for 30 seconds and then I placed my finger but it is not doing any thing. It is again reactivating only after relaunch the popup. 

Can you please help me in fixing these two issues.

**Comment by mjwheatley** [comment]
Issue 1:
This is working as designed.  It is a security feature.  When a new fingerprint is added, it permanently invalidates the previous key.  That way it cannot be used if someone hacked a new fingerprint on the device.  I have publish v0.0.11 to create a new key after authenticating with the backup if their was a failure to initialize the cipher because of an InvalidKeyException.  So if a new fingerprint is added, the user must validate using the backup before they can continue to use fingerprint validation.

Issue 2:
I am unable to replicate this issue.  If I try five times it sends me to the backup validation.  I can cancel or validate and continue.  Either way I have to wait 30 seconds and I am able to continue to validate with the correct finger or attempt another 5 times with an invalid finger.  I was testing using an emulator Nexus 5 API 23 x86.  Please check your Logcat to see if there are any messages related to the finger touch not working.

**Comment by danicholls** [comment]
How would you handle this if you wanted `disableBackup` to be true, then?
