### ISSUE TITLE
Fingerprint prompt non-responding

### ISSUE THREAD

**Issue by shivam-jtg** [mjwheatley/cordova-plugin-android-fingerprint-auth#96]
I setup fingerprint on my login page So that when user open login page and fingerprint sensor is present, Prompt for fingerprint will open. But when prompt has opened and user put the app in the background and bring back to the app a new prompt comes on old prompt and says **Fingerprint operation canceled **. But old prompt is still visible and it is un-responsive means when I touched the finger on fingerprint sensor No action is performed by the plugin and I need to cancel the fingerprint manually.

**Comment by mjwheatley** [comment]
Same issue as https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/issues/95

Perhaps the second prompt is deregistering the first prompt?  You should not open the modal automatically onResume of your application.  You should track if you have opened the modal or not.  That should prevent multiple modals from being displayed.  Otherwise it is the same issue as referenced above.  Please switch to that thread and read my questions and provide any additional information you can.
